name: Deploy Resume Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rebuild and Restart Container
        run: |
          docker compose up -d --build